// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20240618011530_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 3L,
                            CategoryName = "Category",
                            Description = "Integer tempus vulputate felis, id eleifend urna vestibulum sit amet. Pellentesque ligula libero, tincidunt in rutrum a, condimentum eget velit. Vestibulum semper mattis iaculis. Fusce molestie nibh eget ipsum porta, vitae iaculis magna efficitur. Nullam quis mi sit amet erat fermentum tincidunt vel id dolor. Nulla sit amet lacinia ipsum.",
                            ImageURL = "https://github.com/anderson-lda/geekshopping/blob/main/ShoppingImages/3_vader.jpg?raw=true",
                            Name = "Name 3",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Category",
                            Description = "Integer tempus vulputate felis, id eleifend urna vestibulum sit amet. Pellentesque ligula libero, tincidunt in rutrum a, condimentum eget velit. Vestibulum semper mattis iaculis. Fusce molestie nibh eget ipsum porta, vitae iaculis magna efficitur. Nullam quis mi sit amet erat fermentum tincidunt vel id dolor. Nulla sit amet lacinia ipsum.",
                            ImageURL = "https://github.com/anderson-lda/geekshopping/blob/main/ShoppingImages/11_mars.jpg?raw=true",
                            Name = "Name 4",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Category",
                            Description = "Integer tempus vulputate felis, id eleifend urna vestibulum sit amet. Pellentesque ligula libero, tincidunt in rutrum a, condimentum eget velit. Vestibulum semper mattis iaculis. Fusce molestie nibh eget ipsum porta, vitae iaculis magna efficitur. Nullam quis mi sit amet erat fermentum tincidunt vel id dolor. Nulla sit amet lacinia ipsum.",
                            ImageURL = "https://github.com/anderson-lda/geekshopping/blob/main/ShoppingImages/10_milennium_falcon.jpg?raw=true",
                            Name = "Name 5",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Category",
                            Description = "Integer tempus vulputate felis, id eleifend urna vestibulum sit amet. Pellentesque ligula libero, tincidunt in rutrum a, condimentum eget velit. Vestibulum semper mattis iaculis. Fusce molestie nibh eget ipsum porta, vitae iaculis magna efficitur. Nullam quis mi sit amet erat fermentum tincidunt vel id dolor. Nulla sit amet lacinia ipsum.",
                            ImageURL = "https://github.com/anderson-lda/geekshopping/blob/main/ShoppingImages/11_mars.jpg?raw=true",
                            Name = "Name 6",
                            Price = 69.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
